Add file type: .topostats
AFM-SPM/AFMReader pull request #53
Opened 2024-05-14 15:51 UTC by SylviaWhittle

This PR migrates support for the `.topostats` file format from [TopoStats](https://github.com/AFM-SPM/TopoStats) as part of our initiative to migrate all of TopoStats' `io.py` over.

A function for reading hdf5 files and dumping the data into a dictionary is the main logic behind loading these files. Several tests have been added for it.

2024-05-29 10:41 UTC, ns-rse requested changes
Thanks for the comprehensive work on this @SylviaWhittle great to see all the tests and in-line examples as well as the notebook.

Some minor comments, not all for addressing in this Pull Request, have tried to make suggestions where things could be changed though.

2024-05-29 10:41 UTC, ns-rse commented on examples/example_01.ipynb
Not a big issue and certainly not something to do here but we could move the comments in the cells out to Markdown cells.

2024-05-29 10:41 UTC, ns-rse commented on AFMReader/topostats.py
> +            logger.info(f"TopoStats file version: {file_version}")
Perhaps include `filename` as is done in the `logger.error()` below so people know what file is which version?

```suggestion
            logger.info(f"[{filename}] TopoStats file version : {file_version}")
```

2024-05-29 10:41 UTC, ns-rse commented on tests/test_topostats.py
> +            0.1,
Not for this PR but as we move forward with developing and standardising the `.topostats` file format and defining versions we should be looking to document precisely what each file version corresponds to with a detailed technical specification. A useful article on this is [A practical guide to writing technical specs - Stack Overflow](https://stackoverflow.blog/2020/04/06/a-practical-guide-to-writing-technical-specs/)

2024-05-29 10:41 UTC, ns-rse commented on tests/test_topostats.py
> +            "sample_0.topostats",
Perhaps pedantic but to make it easier to read/understand what's what in the `tests/resources/` directory we could use a nomenclature that reflects the version.

```suggestion
            "sample_0_1.topostats",
```

...would indicate the version `0.1` (would also require renaming `sample_0.topostats` > `sample_0_1.topostats`).

2024-05-29 12:15 UTC, ns-rse commented
Thanks for testing this @MaxGamill-Sheffield 

> On testing and reviewing this, I saw that there was no space for the .topostats files in the example_0.ipyb so I have added that.

You commit #0fdb9cc18 introduced a number of unintended changes to the notebook, the cell `execution_count` was now non-zero. I think this is because you haven't enabled `pre-commit` on this repository. In this instance its not a problem as `pre-commit.ci` is able to run the `nbstripout` hook and commit the changes to this PR directly but if you ever do additional work on this repository it would be worth enabling `pre-commit` locally so that all the hooks run prior to commits.

```bash
pre-commit install
```

...should do the trick.

2024-06-06 21:45 UTC, SylviaWhittle commented
I think I've addressed the comments? Let me know if I've forgotten something.

I think the documentation on the format could be done in another PR? Or should I add it to this one?

2024-06-07 09:43 UTC, ns-rse commented
> I think the documentation on the format could be done in another PR? Or should I add it to this one?

Definitely a separate issue and one that would benefit from wider discussion as to what people actually want to have in `.topostats` files. Garnering input from the wider community (beyond the Pyne lab) would be really useful in planing the formats specification.

2024-06-07 19:02 UTC, merged